name: ci
on:
  push:
  pull_request:
    types: [opened, reopened]
env:
  PRODUCTION_BRANCH: refs/heads/master
  DEVELOP_BRANCH: refs/heads/develop
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
jobs:
  gatekeep:
    name: Determine if Build & Deploy is needed
    outputs:
      proceed: ${{ steps.determine_proceed.outputs.proceed }}
    runs-on: ubuntu-18.04
    if: github.event_name == 'push'
    steps:
      - shell: python
        id: determine_proceed
        run: |
          import os
          ref = os.environ['GITHUB_REF']
          prod = os.environ['PRODUCTION_BRANCH']
          if ref == prod:
            print('::set-output name=proceed::true')
          else:
            print('::set-output name=proceed::false')
  deploy:
    name: Fake deploy
    runs-on: ubuntu-18.04
    needs: [gatekeep]
    if: needs.gatekeep.outputs.proceed == 'true'
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: Cache Node.js modules
          uses: actions/cache@v2
          with:
            # npm cache files are stored in `~/.npm` on Linux/macOS
            path: ~/.npm
            key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.OS }}-node-
              ${{ runner.OS }}-
        - name: Install NPM
          run: npm ci
        - name: Test action
          run: echo "test action!"
        - name: Release
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          run: npx semantic-release